#!/bin/bash

# exit at the first error
set -o errexit

srcdir=src
scriptdir=scripts

cd $scriptdir

# Make the data
datadir=data-rcr
wipedata=1
if [[ -d $datadir && -f $datadir/alldata.dat && -f $datadir/alldata-mt-2.dat
     && -f $datadir/alldata-mt-4.dat && -f $datadir/alldata-mt-8.dat ]]; then
   read -p "All data appears to be present, reuse it (not recommended)? " -n 1 -r
   echo
   if [[ $REPLY =~ ^[Yy]$ ]]; then
      echo "OK, reusing existing data"
      wipedata=0 # do dangerous stuff
   fi
fi
if [[ $wipedata -ne 0 ]]; then
    # Clean everything and regenerate
    echo "Wiping any existing data"

    # Compile programs
    cd ../$srcdir
    make clean
    make main
    make main-mt
    cd ../$scriptdir
    if [ ! -L main-mt ]; then
        ln -s ../src/main-mt .
    fi
    if [ ! -L main ]; then
        ln -s ../src/main .
    fi

    # generate the data
    rm -rf $datadir
    mkdir $datadir
    python experiments-rcr.py
fi

# Make the figures
figdir=figs-rcr
if [ -d $figdir ]; then
    rm -f $figdir/*.pdf $figdir/*.svg
else
    mkdir $figdir
fi
python snarf-rcr-svg.py
python snarf-rcr-pdf.py

echo "All done. Look at scripts/figs-rcr/index.html."

echo "Now making a tarball that you can send me if you want..."
lscpu > $figdir/lscpu.txt
cat /proc/cpuinfo > $figdir/cpuinfo.txt
cd ..
tar cf rcr.tgz $scriptdir/$figdir
echo "If you got this far, I would love to see the output."
echo "Help out by sending ./rcr.tgz to morin@scs.carleton.ca"


