#!/bin/bash -ex

cd src
make clean
make main
make main-mt
cd ../scripts
if [ -d run_data ]; then
    rm -f run_data/*
else
    mkdir run_data
fi
if [ ! -L main ]; then
    ln -s ../src/main .
fi
if [ ! -L main-mt ]; then
    ln -s ../src/main-mt .
fi
python experiments-2.py
if [ -d figs-2 ]; then
    rm -f figs-2/*
else
    mkdir figs-2
fi
python snarf-2.py

echo "All done. Look at the PDF files in the figs-2/ directory"


